### ISSUE TITLE
Server running on 127.0.0.1

### ISSUE THREAD

**Issue by felixkempf** [macecchi/pebble-itunesify-remote-osx#3] opened 2015-09-19 18:28 UTC
Hey, when I start the app on my MacBook with 10.8.5 the service runs on 127.0.0.1.
The pebble app naturally does not work when I type that into the settings.

**Comment by macecchi** [comment] 2015-09-20 15:05
Hi,

There must be an issue checking the Mac’s IP using this version of OS X.

Can you check the computer’s IP address manually then? You can Option + click the Wi-Fi icon on your Mac’s status bar or find it in Settings > Network. Then type this address on the Pebble app settings.

Kind regards,
Mario

**Comment by felixkempf** [comment] 2015-09-21 08:00
Oh, It's that easy. Thanks.
Spotify remote works now, iTunes does unfortunately not. 

To validate if thats an issue with the OS X version, I installed the app on another Mac with 10.9.5.
But there, the pebble app notifies me, that I use an old version of the mac app, besides having downloaded and installed version 1.2 from 24 days ago and also building it myself from source.

I don't expect you to fix that, just wanted to let you know of that rather specific problem.
I should probably update OS X anyway.

Warm Greetings
Felix

**Comment by macecchi** [comment] 2015-09-21 17:08
Thanks for letting me know, Felix :)

I'll close this issue then, ok? I can only guess iTunes isn't working because of the OS X version, as this is working fine everywhere else. Unfortunately I don't think I have any means to debug this locally... If you want to contribute, I can explain you better to see if you can fix it yourself. ;)

I'll see if I can reproduce the other bug, although that is a weird one. The alert shows when the watch can't fetch the current app selected on the mac, which is a feature from the latest version, and only shows the alert if it can reach the Mac and it returns a 404 error, which would happen if running an old version of the app. It shouldn't be related to the OS X version, but idk...

**Closed by macecchi** 2015-09-21 17:08 UTC

**Comment by felixkempf** [comment] 2015-09-21 21:46
The thing with localhost could be tracked to my hosts file, where the string returned by require('os').hostname() was bound to 127.0.0.1 ^^

I think I could track back the problems with iTunes to the osascript module of airtoxin/local-itunes, which gets the commands in JacaScript, which is only supported since Yosemite, instead of AppleScript like the spotify module. Therefor, Spotify works and iTunes doesn't.

**Comment by macecchi** [comment] 2015-10-01 05:54
Hey @felixkempf, I totally forgot to reply to you.

You are right. I just picked the easiest-to-use modules to communicate with Spotify and iTunes and I didn't pay attention to this. I'll at least mention it on the readme file if I don't switch to a compatible module.

Thanks again for the help :)
